version: 2.1
jobs:
  linting:
    docker:
      - image: python:3.7-buster

    working_directory: /usr/local/src/botto_app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -U black lxml mypy pylint
            pip install -r requirements.txt

      - run:
          name: Run black formatting checks
          command: black . --check
          when: always

      - run:
          name: Run mypy typing checks
          command: mypy . --xml-report=/reports/mypy
          when: always

      - run:
          name: Run pylint linting checks
          command: |
            mkdir /reports/pylint
            pylint botto --reports=y 2>&1 | tee /reports/pylint/report.txt
          when: always

      - store_test_results:
          path: /reports

      - store_artifacts:
          path: /reports
          destination: reports

workflows:
  version: 2.1
  build:
    jobs:
      - linting