#!/bin/sh

echo "Checking for Python syntax errors or undefined names with flake8..."
pipenv run flake8 botto --count --select=E9,F63,F7,F82 --show-source --statistics
echo ""

echo "Checking other style errors with flake8..."
pipenv run flake8 botto --count --statistics
echo ""

echo "Checking static typing with mypy..."
pipenv run mypy botto
echo ""

echo "Checking Python and style errors with pylint..."
pipenv run pylint botto/**/*.py
echo ""

echo "Checking formatted code with black..."
pipenv run black botto --check -l 100 --exclude migrations
echo ""
